---
version: "2"
services:
  nginx:
    image: nginx:1.13.6
    ports:
      - 3000:3000
      - 8080:80
    volumes:
      - $PWD/learning_app:/opt/app:ro
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/theia:/opt/theia
    depends_on:
      - app
      - theia
  theia:
    build: theia
    volumes:
      - $PWD/learning_app:/home/project
  app:
    build: learning_app
    expose:
      - 3000
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432
    depends_on:
      - postgres
    volumes:
      - $PWD/learning_app/:/app/
  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
  redis:
    image: redis
    ports:
      - 6379:6379
